pipeline {
    agent any
                   environment {
                       AWS_ACCESS_KEY_ID = credentials('Orchid_AWS')
                       AWS_SECRET_ACCESS_KEY = credentials('Orchid_AWS')
                    }
        stages {
            stage ('Network') {
                when {
                    expression {
                        Network == 'True'
                    }
                }
                steps {
                     dir ('env/management/network') {
                    task()
                        }
                }
            }
        stage ('Openvpn') {
            when {
                expression {
                    Openvpn == 'True'
                }
            }
            steps {
                dir('env/management/openvpn') {
                    task()
                }
            }
        }
        stage ('internal_alb') {
            when {
                expression {
                    ALB == 'True'
                }
            }
            steps {
                dir('env/management/internal_alb') {
                    task()
                }
            }
        }
        stage ('Buildpiper') {
           when {
                expression {
                    BP == 'True'
                }
            }
            steps {
                dir('env/management/buildpiper') {
                    task()
                }
            }
}
       stage ('EKS') {
           when {
                expression {
                    EKS == 'True'
                }
            }
            steps {
                dir('env/management/EKS') {
                    task()
                }
            }
}
}
}

void task() {
     sh 'export AWS_ACCESS_KEY="$AWS_ACCESS_KEY_ID"'
     sh 'export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"'
     sh ' export AWS_REGION=ap-south-1'
     sh 'terraform init'
     sh 'terraform validate'
     sh 'terraform plan'    
}