@Library('opstree-library@buildpiper_infra')

def terraformbuildpiper = new org.opstree.ci.terraformCI.buildPiperInfraSetup()

node{
   environment {
                       AWS_ACCESS_KEY_ID = credentials('AWS')
                       AWS_SECRET_ACCESS_KEY = credentials('AWS')
                }                
  terraformbuildpiper.call(configFilePath: "env/management/configuration",AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID", AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY")
}