pipeline {
    agent any

    environment {
        network = "$value"
    }
stages {
    stage('Network') {
        when {
            environment(name: "network", value: "true")
        }
        steps{
          dir ('env/management/network') {
              sh 'terraform init'
              sh 'terraform plan'
              sh 'terraform validate'
              sh 'terraform plan'
              sh 'terraform apply'
          }
        }
    }
}
}