module "vpc" {
  source                  = "OT-CLOUD-KIT/vpc/aws"
  version                 = "0.0.6"
  cidr_block              = var.cidr_block
  enable_vpc_logs         = false
  public_subnets_cidr     = var.public_subnets_cidr
  pvt_zone_name           = var.pvt_zone_name
  private_subnets_cidr    = var.private_subnets_cidr
  avaialability_zones     = local.subnet_az
  logs_bucket             = var.logs_bucket
  logs_bucket_arn         = var.logs_bucket_arn
  tags                    = var.tags
  public_web_sg_name      = var.public_web_sg_name
  alb_certificate_arn     = var.alb_certificate_arn
  enable_pub_alb_resource = false
  vpc_name                = var.vpc_name
  igw_name                = var.igw_name
  pub_rt_name             = var.pub_rt_name
  pub_subnet_name         = var.pub_subnet_name
  nat_name                = var.nat_name
  pvt_rt_ame              = var.pvt_rt_ame
  pvt_subnet_name         = var.pvt_subnet_name
  alb_name                = var.alb_name
}
